---
title: Stackbit Ampersand Theme
baseURL: "/"
params:
  layout_style: grid
  palette: green
  header:
    title: Richard's Forestry Test
    logo_img: "/images/182479.jpg"
    has_nav: true
  footer:
    content: "&copy; All rights reserved."
    links:
    - text: Made with Stackbit
      url: https://www.stackbit.com
      new_window: true
    has_social: true
disableKinds:
- RSS
